# Documentation https://golangci-lint.run/usage/linters

issues:
  new: true
  fix: true
  new-from-rev: 1f97af5d186226fb12dec0beaaee1f61abad8aef

run:
  timeout: 10m
  issues-exit-code: 1
  tests: false
  skip-dirs-use-default: true

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errname
    - exhaustive
    - exportloopref
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gomnd
    - gosec
    - gosimple
    - govet
    - grouper
    - ifshort
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - nlreturn
    - nolintlint
    - predeclared
    - staticcheck
    - structcheck
    # - tagliatelle # remove this for existing projects
    - typecheck
    - unconvert
    - unused
    - varcheck
    - wastedassign
    - whitespace
    - wsl

linters-settings:
  gocyclo:
    min-complexity: 75
  goimports:
    local-prefixes: github.com/RocketChat/filestore-migrator
  misspell:
    locale: US
  nlreturn:
    block-size: 2
  tagliatelle:
    case:
      use-field-name: true
      rules:
        json: camel
        yaml: camel
        bson: camel
  wsl:
    allow-assign-and-call: false
    allow-multiline-assign: false
    force-err-cuddling: true
