database:
  connectionString: "mongodb://127.0.0.1:27017/customer"
  database: "customer"
source:
  type: GridFS
tempFileLocation: "files"
destination:
  type: "AmazonS3"
  AmazonS3:
    endpoint: "s3.amazonaws.com"
    bucket: "rocketchat"
    accessId: id
    accessKey: key
    region: us-east-1
    useSSL: true
