binary_name=filestore-migrator
version=latest

# Build the tool binary
build: clean
	@CGO_ENABLED=0 go build -v -a -ldflags "-X main.version=${version}" -o ${binary_name} ./cmd/filestore-migrator/

install: build
	mv ${binary_name} $$GOPATH/bin/${binary_name}

# Delete all artifacts generated by the build routines.
clean:
	@rm -f ${binary_name}

# Build the tool docker image.
docker:
	docker build -t ${binary_name}:${version} .

# Build and execute the tool binary.
run: build
	${binary_name}
